### PR TITLE
Delete Yarn lockfile

### PR DESCRIPTION
**Pull request by vlyr**
**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**
This PR aims to delete Yarn's lockfile from the codebase. As Yarn is not used with this project, it's fine to delete it. Yarn's lockfile can also cause useless merge conflicts during PRs, which must be resolved manually.  
**Semantic versioning classification:**

- [ ] This PR changes the framework's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [x] This PR **only** includes non-code changes, like changes to README, etc.

### CODE REVIEW

**Comment by seanjhardy** [comment]
So you just.... deleted the entire file 👀does it still work?

**Review by swatarianess — APPROVED** [review]

**Comment by vlyr** [comment]
> So you just.... deleted the entire file eyesdoes it still work?

Yup, works perfectly fine (at least on my machine :wink: ).

**Review by swatarianess — APPROVED** [review]

**Review by seanjhardy — DISMISSED** [review]

**Comment by seanjhardy** [comment]
ffs that removed the approvals

**Review by seanjhardy — DISMISSED** [review]

**Comment by seanjhardy** [comment]
Sorry I've actually polluted this PR somehow

**Review by seanjhardy — APPROVED** [review]

**Review by swatarianess — APPROVED** [review]

**Pull request merged**
