### PR TITLE
Add task list

### PR DESCRIPTION
**Pull request by vlyr**
**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**
This PR adds a sample task list command, allowing users to view and edit the state of tasks related to the skills they've started. This PR also removes ambiguity from field names in the skill struct, as well as adds extra documentation for them.
**Semantic versioning classification:**

- [x] This PR changes the framework's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

### CODE REVIEW

**Review by seanjhardy — CHANGES_REQUESTED** [review]
In skill.js the "time" property is equivalent to the new "frequency" property, instead of adding a new parameter, please rename it to frequency

**Comment by seanjhardy** [comment]
Actually I'm mistaken, they're all used, please rename the docs for clarity about the purpose of time if you can

**Comment by seanjhardy** [comment]
I'd rename "time" to "interval", "no deadline" to "ongoing", and maybe change the time limit to the integer number of days because I think that's what we'll be tracking in the database to make processing easier

**Comment by vlyr** [comment]
All that should be done now, lmk if I missed something.

**Comment by seanjhardy** [comment]
Looking good, just two things, "change the time limit to the integer number of days because I think that's what we'll be tracking in the database to make processing easier" aka change each of "x1 MONTH(S)" -> 30, "x1 WEEK(S)" -> 7 etc. And add documentation for frequency parameter

**Comment by vlyr** [comment]
Right, that should be it.

**Review by seanjhardy — APPROVED** [review]

**Review by swatarianess — APPROVED** [review]

**Comment by thewildofficial** [comment]
wait, has the branches merged or am i trippin'

**Pull request merged**
